linters:
  enable:
    - bodyclose
    - durationcheck
    - copyloopvar
    - gomoddirectives
    - prealloc
    - reassign
    - gocritic
    - gofmt
    - govet
    - gosimple
    - unconvert
    - unparam
    - unused
  disable:
    - errcheck
